controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\User;
use app\models\Message;
use app\models\Game;
use app\models\Move;
use yii\data\ActiveDataProvider;
use yii\helpers\Json;
use yii\helpers\Url;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (!parent::beforeAction($action)) {
            return false;
        }
        if (Yii::$app->user->isGuest) {
            Yii::$app->language = 'en-US';
        } else {
            Yii::$app->language = Yii::$app->user->identity->language;
        }

        return true;
    }

    public function actionChangeLanguage($lang)
    {
        $user = User::findOne(Yii::$app->user->id);
        $user->language = $lang;
        if($user->validate()){
            $user->save();
        }

        return $this->redirect(Url::to(['site/index']));
    }

    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(Url::to(['site/login-form']));
        }

        $availableUsers = new ActiveDataProvider([
            'query' => User::findAvailableUsers(),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);

        $messagesFrom = new ActiveDataProvider([
            'query' => Message::findMessagesFrom(),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);

        $messagesTo = new ActiveDataProvider([
            'query' => Message::findMessagesTo(),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);

        $activeGames = new ActiveDataProvider([
            'query' => Game::findActiveGames(),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);

        $previousGames = new ActiveDataProvider([
            'query' => Game::findPreviousGames(),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);

        $rating = Yii::$app->user->identity->rating;

        return $this->render('index', [
            'availableUsers' => $availableUsers,
            'messagesTo' => $messagesTo,
            'messagesFrom' => $messagesFrom,
            'activeGames' => $activeGames,
            'previousGames' => $previousGames,
            'rating' => $rating
        ]);
    }

    public function actionLoginForm()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new LoginForm();
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogin()
    {
        $errors = [];
        $model = new LoginForm();
        $model->attributes = Yii::$app->request->post();
        if ($model->validate()) {
            $model->login();
        } else {
            $errors = $model->getErrors();
        }

        return Json::encode($errors);
    }

    public function actionRegister()
    {
        $errors = [];
        $model = new LoginForm();
        $model->attributes = Yii::$app->request->post();
        if ($model->validate()) {
            $model->signIn();
        } else {
            $errors = $model->getErrors();
        }

        return Json::encode($errors);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->redirect(Url::to(['site/login-form']));
    }

    public function actionInvite($id)
    {
        $userId = Yii::$app->user->id;
        $message = Message::find()
            ->where([
                'from' => $userId,
                'to' => $id,
                'answer' => false,
                'active' => true
            ])
            ->one();

        if(!$message){
            $message = new Message();
            $message->from = $userId;
            $message->to = $id;
        } else {
            $message->answer = null;
        }

        if($message->validate()){
            $message->save();
        }

        return $this->redirect(Url::to(['site/index']));
    }

    public function actionDeleteMessage($id)
    {
        Message::findOne($id)->delete();
        return $this->redirect(Url::to(['site/index']));
    }

    public function actionConfirm($id)
    {
        $transaction = Yii::$app->getDb()->beginTransaction();
        try {
            $message = Message::findOne($id);
            $message->answer = true;
            $message->active = false;
            if ($message->validate()) {
                $message->save();
            }

            $game = new Game();
            $game->message_id = $message->message_id;
            $game->first_gamer_id = $message->to;
            $game->second_gamer_id = $message->from;
            $game->current = $message->to;
            if ($game->validate()) {
                $game->save();
            }

            $transaction->commit();
        } catch(\Exception $e) {
            $transaction->rollBack();
            throw $e;
        }

        return $this->redirect(Url::to(['site/index']));
    }

    public function actionReject($id)
    {
        $message = Message::findOne($id);
        $message->answer = false;
        if ($message->validate()) {
            $message->save();
        }

        return $this->redirect(Url::to(['site/index']));
    }

    public function actionPlay($id, $show = false)
    {
        $game = Game::find()->where(['game_id' => $id])->asArray()->one();
        $moves = Move::find()
            ->select('*, users.username')
            ->innerJoin('users', 'users.id = moves.gamer_id')
            ->where(['game_id' => $id])
            ->orderBy('move_id')
            ->asArray()->all();
        $moves = array_map(function($move) use ($game){
                if($move['gamer_id'] === $game['first_gamer_id']){
                    $move['symbol'] = 'x';
                } else {
                    $move['symbol'] = 'o';
                }
                return $move;
            },
            $moves);

        if($show) {
            $symbol = '';
        } else {
            $symbol = ((int)$game['first_gamer_id'] === Yii::$app->user->id) ? 'x' : 'o';
        }

        return $this->render('game', [
            'game_id' => $game['game_id'],
            'current' => Yii::$app->user->id,
            'moves' => $moves,
            'symbol' => $symbol
        ]);
    }

    public function actionMakeMove()
    {
        $request = Yii::$app->request->post();
        $transaction = Yii::$app->getDb()->beginTransaction();
        try {
            $game = Game::findOne($request['game_id']);
            if($game->first_gamer_id === (int)$request['gamer_id']){
                $game->previous = $game->first_gamer_id;
                $game->current = $game->second_gamer_id;
            } else {
                $game->previous = $game->second_gamer_id;
                $game->current = $game->first_gamer_id;
            }
            if ($game->validate()) {
                $game->save();
            }

            $move = new Move();
            $move->game_id = (int)$request['game_id'];
            $move->gamer_id = (int)$request['gamer_id'];
            $move->abs = (int)$request['abs'];
            $move->ord = (int)$request['ord'];
            if ($move->validate()) {
                $move->save();
            }

            $transaction->commit();
        } catch(\Exception $e) {
            $transaction->rollBack();
            throw $e;
        }

        $result = $this->checkResult($game->game_id);
        if(!empty($result)) $this->finishGame($game->game_id);


        return Json::encode($result);
    }

    private function checkResult($id)
    {
        $winner = Game::findWinner($id);
        return $winner;
    }

    private function finishGame($id)
    {
        $transaction = Yii::$app->getDb()->beginTransaction();
        try {
            $game = Game::findOne($id);
            $game->winner = $game->previous;
            if ($game->validate()) {
                $game->save();
            }

            $user = User::findOne($game->winner);
            $user->rating += 1;
            if ($user->validate()) {
                $user->save();
            }

            $transaction->commit();
        } catch(\Exception $e) {
            $transaction->rollBack();
            throw $e;
        }
    }

    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/about.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
$this->title = Yii::t('app', 'About Go-Moku');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Yii::t('app', 'Go-Moku is ancient chinese game.') ?>
    </p>
</div>

views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/game.php
<?php
use yii\helpers\Url;
use yii\web\View;
?>

<?php
$this->title = Yii::t('app', 'Game');
?>
<div style="float: right; width: 500px; height: 700px;">
    <h3><?= Yii::t('app', 'Game Turns') ?></h3>
    <?php
        $counter = 1;
        foreach($moves as $move){
    ?>
        <p><?="{$counter}. {$move['username']} : X - {$move['abs']}, Y - {$move['ord']}"?></p>
    <?php
            $counter += 1;
        }
    ?>
    <?php
        if(empty($symbol)) {
    ?>
        <h4><?= Yii::t('app', '{username} is winner!', ['username' => $moves[$counter-2]['username']]) ?></h4>
    <?php
        }
    ?>
</div>

<table border="1" cellspacing="0" cellpadding="8"  style="border-color:#cc0000">
<?php
    for($x = 1; $x <= 3; $x++){
?>
    <tr>
        <?php
            for($y = 1; $y <= 3; $y++){
                $content = '';
                $class = 'active';
                foreach($moves as $move){
                    if((int)$move['abs'] === $x && (int)$move['ord'] === $y){
                        $content = $move['symbol'];
                        $class = 'inactive';
                        break;
                    }
                }
        ?>
            <td class="<?=$class ?>" width="200" height="200" style="border-color:#cc0000; font-size:100pt; text-align: center;" data-abs = '<?=$x ?>' data-ord = '<?=$y ?>'>
                <?php
                    echo $content;
                ?>
            </td>
        <?php
            }
        ?>
    </tr>
<?php
    }
?>
</table>

<?php
if(!empty($symbol)) {
    $this->registerJs('
        function editTable(){
            $("td.active").bind("click.editTable", function(event){
                    $(event.target).text("' . $symbol . '");
                    $("*").unbind("click.editTable");
                    var abs = $(event.target).attr("data-abs");
                    var ord = $(event.target).attr("data-ord");
                    $.post("' . Url::to(["site/make-move"], true) . '", {
                            game_id: "' . $game_id . '",
                            abs: abs,
                            ord: ord,
                            gamer_id: "' . $current . '"
                        }
                    ).success(function(data){
                            var data = jQuery.parseJSON(data);
                            if(data.length !== 0){
                                alert(data);
                            }
                            window.location = "' . Url::to(["site/index"], true) . '"
                        }
                    );
                }
            );
        }
        editTable();
    ', View::POS_END);
}
?>

views/site/index.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;
?>

<?php
$this->title = 'GameCenter';
?>

<h3 style="float: right;"><?= \Yii::t('app', 'Your rating: {rating}', ['rating' => $rating]) ?></h3>

<h3><?= \Yii::t('app', 'Available Users:') ?></h3>
<div>
<?= GridView::widget([
    'dataProvider' => $availableUsers,
    'showHeader' => true,
    'summary'=>'',
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        'username',
        'rating',
        ['class' => 'yii\grid\ActionColumn',
            'buttons' => [
                'invite' => function ($url,$model,$key) { return Html::a(\Yii::t('app', 'Invite this user'), Url::to(['site/invite', 'id' => $model->id]));},
            ],
            'header' => \Yii::t('app', 'Action'),
            'template' => '<div>{invite}</div>',
            'headerOptions'=>['class' => 'custom-header'],
        ],
    ]
]);
?>
</div>

<h3><?= \Yii::t('app', 'Your invitations:') ?></h3>
<div>
<?= GridView::widget([
    'dataProvider' => $messagesFrom,
    'showHeader' => true,
    'summary'=>'',
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        'to_user',
        'user_answer',
        ['class' => 'yii\grid\ActionColumn',
            'buttons' => [
                'invite' => function ($url,$model,$key) {
                    if($model->user_answer === \Yii::t('app', 'Rejected')){
                        return Html::a(\Yii::t('app', 'Invite again'), Url::to(['site/invite', 'id' => $model->to]));
                    } else {
                        return \Yii::t('app', 'Wait for answer');
                    }
                },
                'delete' => function ($url,$model,$key) { return Html::a(\Yii::t('app', 'Delete'), Url::to(['site/delete-message', 'id' => $model->message_id]));},
            ],
            'header' => \Yii::t('app', 'Action'),
            'template' => '<div>{invite} | {delete}</div>',
            'headerOptions'=>['class' => 'custom-header'],
        ],
    ]
]);
?>
</div>

<h3><?= \Yii::t('app', 'Invitations to you:') ?></h3>
<div>
    <?= GridView::widget([
        'dataProvider' => $messagesTo,
        'showHeader' => true,
        'summary'=>'',
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'from_user',
            ['class' => 'yii\grid\ActionColumn',
                'buttons' => [
                    'yes' => function ($url,$model,$key) { return Html::a(\Yii::t('app', 'Yes'), Url::to(['site/confirm', 'id' => $model->message_id]));},
                    'no' => function ($url,$model,$key) { return Html::a(\Yii::t('app', 'No'), Url::to(['site/reject', 'id' => $model->message_id]));},
                ],
                'header' => \Yii::t('app', 'Action'),
                'template' => '<div>{yes} | {no}</div>',
                'headerOptions'=>['class' => 'custom-header'],
            ],
        ]
    ]);
    ?>
</div>

<h3><?= \Yii::t('app', 'Your active games:') ?></h3>
<div>
    <?= GridView::widget([
        'dataProvider' => $activeGames,
        'showHeader' => true,
        'summary'=>'',
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'user1',
            'user2',
            'current_name',
            ['class' => 'yii\grid\ActionColumn',
                'buttons' => [
                    'play' => function ($url,$model,$key) {
                            if($model->current == \Yii::$app->user->id){
                                return Html::a(\Yii::t('app', 'Play'), Url::to(['site/play', 'id' => $model->game_id]));
                            } else {
                                return \Yii::t('app', 'Not your turn');
                            }
                        },
                ],
                'header' => \Yii::t('app', 'Action'),
                'template' => '<div>{play}</div>',
                'headerOptions'=>['class' => 'custom-header'],
            ],
        ]
    ]);
    ?>
</div>

<h3><?= \Yii::t('app', 'Your previous games:') ?></h3>
<div>
    <?= GridView::widget([
        'dataProvider' => $previousGames,
        'showHeader' => true,
        'summary'=>'',
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'user1',
            'user2',
            'winner_name',
            ['class' => 'yii\grid\ActionColumn',
                'buttons' => [
                    'show' => function ($url,$model,$key) {return Html::a(\Yii::t('app', 'Show'), Url::to(['site/play', 'id' => $model->game_id, 'show' => true]));},
                ],
                'header' => \Yii::t('app', 'Action'),
                'template' => '<div>{show}</div>',
                'headerOptions'=>['class' => 'custom-header'],
            ],
        ]
    ]);
    ?>
</div>

views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
use yii\web\View;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'username')->textInput(['id' => 'username']) ?>

    <?= $form->field($model, 'password')->passwordInput(['id' => 'password']) ?>

    <?= $form->field($model, 'rememberMe', [
        'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
    ])->checkbox(['id' => 'rememberMe']) ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::a(
                'Login', '#',
                [
                    'class' => 'btn btn-primary',
                    'onclick' => 'submit("'. Url::to(["site/login"]) . '");'
                ]
            )
            ?>
            <?= Html::a(
                'Sign in', '#',
                [
                    'class' => 'btn btn-primary',
                    'onclick' => 'submit("'. Url::to(["site/register"]) . '");'
                ]
            )
            ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
</div>

<?php
    $this->registerJs('
        function submit(url){
            var username = $("#username").val();
                var password = $("#password").val();
                var rememberMe = $("#rememberMe").val();
                $.post(url, {
                        username: username,
                        password: password,
                        rememberMe: rememberMe
                    }
                ).success(function(data){
                            var data = jQuery.parseJSON(data);
                            if(data.length == 0){
                                window.location = "' . Url::to(["site/index"], true) . '"
                            }
                        });
        }', View::POS_END);
?>